version: '3'
services:
  scavi:
    build: .
    image: maayanlab/scv:1.0.7
    ports:
      - 5000:5000
    environment:
      - APPLICATION_DEFAULT_CREDENTIALS=${APPLICATION_DEFAULT_CREDENTIALS}
      - ENTER_POINT=${ENTER_POINT}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - MONGOURI=${MONGOURI}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - debug=${debug}
      - ORIGIN=${ORIGIN}
      - HOSTNAME=${HOSTNAME}
      - GENE_SET_LIBRARIES=${GENE_SET_LIBRARIES}
    volumes:
      - ./data:/my_application/data

  mongohost:
    image: mongo

  mysqlhost:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
